# Generated by Django 4.2.5 on 2023-10-11 06:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dms", "0002_message_updated_at_alter_chatroom_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="Text",
            new_name="text",
        ),
    ]
