# Generated by Django 4.2.5 on 2023-10-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("price_per_night", models.PositiveIntegerField()),
                ("description", models.TextField()),
                ("address", models.CharField(max_length=140)),
                (
                    "max_guest_number",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="최대 인원수 이상으로는 숙박이 불가능 합니다."
                    ),
                ),
                ("pet_allowed", models.BooleanField(default=True)),
            ],
        ),
    ]
