# Generated by Django 4.2.5 on 2023-10-11 06:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="rooms",
        ),
    ]
