# Generated by Django 4.2.5 on 2023-09-26 12:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("houses", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="house",
            old_name="prince",
            new_name="price",
        ),
    ]
