# Generated by Django 4.2.5 on 2023-09-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("houses", "0003_rename_price_house_price_per_night"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="max_guest_number",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="house",
            name="pet_allowed",
            field=models.BooleanField(default=True),
        ),
    ]
