# Generated by Django 4.2.5 on 2023-11-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medias", "0003_remove_photo_name_video_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="file",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.URLField(),
        ),
    ]
