# Generated by Django 4.2.5 on 2023-10-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(editable=False, max_length=150)),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[("room", "Room"), ("experience", "Experience")],
                        default="",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "descriptions",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                ("check_in", models.DateField(blank=True, null=True)),
                ("check_out", models.DateField(blank=True, null=True)),
                ("experience_time", models.DateTimeField(blank=True, null=True)),
                ("guests", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("paid", "Paid"),
                            ("canceled", "Canceled"),
                            ("completed", "Completed"),
                        ],
                        max_length=15,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
